name: irish_locums
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  animations: ^2.0.4
  gap: ^2.0.0
  flutter_svg: ^1.1.0
  dots_indicator: ^2.0.0
  readmore: ^2.2.0
  dotted_border: ^2.0.0+3
  dropdown_formfield: ^0.1.4
  percent_indicator: ^4.2.2
  calendar_agenda: ^0.0.2+3
  table_calendar: ^3.0.8
  syncfusion_flutter_datepicker: ^20.3.58

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf


